---
title: "Shrock2020_virscan_regression"
output: html_notebook
---


```{r}
library(Peptides)
library(readxl)
library(dplyr)
library(readr)
library(tidyr)
library(tibble)
library(data.table)
library(glmnet)
# set working directory to where script is
here::i_am("scripts/Shrock2020_regression.Rmd")
library(here)
source("../scripts/peptides.R")

```


```{r}
# load processed merged virscan data containing covid, hospitalization, peptide-zscores for each patient sample
pat_meta_vir_z <- readRDS(file = here::here("./results/processed", "pat_meta_vir_z_2024-10-22.rds"))
```

```{r}

# Convert to a tibble if needed
pat_meta_vir_z <- as_tibble(pat_meta_vir_z)

# Pivot to wide format using pivot_wider
pivot_pat_meta_vir_z <- pat_meta_vir_z %>%
  pivot_wider(names_from = id, 
              values_from = z_score)

pivot_pat_meta_vir_z <- pivot_pat_meta_vir_z %>% mutate(COVID19_status = if_else(COVID19_status == "positive", 1, 0),
                                  Hospitalized = if_else(Hospitalized == "hospitalized", 1, 0))
                                  

# View the resulting pivoted data
head(pivot_pat_meta_vir_z)
```

```{r}
## save pat_meta_vir_z; ready to use as input to model
save_as_rds(pivot_pat_meta_vir_z, "pat_meta_vir_z_input", "./data/")
```


```{r}

# # response:, covariates: all z scores
NUM_PEPTIDES = 115753
covstat_zscores_str <- paste("COVID19_status~", paste(1:NUM_PEPTIDES, collapse="+"), sep = "")
# lm_z_means_feats_sc <- lm(lm_str, data = vir_merged)
# summary(lm_z_means_feats_sc)
# save_as_rds(lm_z_means_feats_sc, "lm_z_means_feats_sc", "./results/")

lr_covstat_zscores <- glm()
# log_model <- glm()

## Try LR just because, try  LASSO, Elastic Net
## Otherwise, want to try dim reduction first 


set.seed(1031)
## Fit LASSO
## find penalty \lambda by cross-validation by minimizing MSE
z_scores <- as.matrix(pivot_pat_meta_vir_z[, -c(1:5)]) # just the z-score columns
cov_stat <- pivot_pat_meta_vir_z$COVID19_status
lasso_cov_z <- cv.glmnet(x=z_scores, y=cov_stat, alpha=1,family="binomial",type.measure = "mse")
```

```{r}

plot(lasso_cov_z)
title(main="LASSO covid status vs. all z-scores")

```

```{r}
l_min <- lasso_cov_z$lambda.min
coef <- coef(lasso_cov_z, s="lambda.min")
nonzero_coef <- coef[coef[,1]!=0,][-1] # also exclude intercept
print(nonzero_coef)
```


```{r}

## Relating LASSO coefficients to peptides
vir_lib <- readRDS(file = here::here("./data/processed", "vir_lib_2024-10-24.rds"))
cov_lib <- readRDS(file = here::here("./data/processed", "cov_lib_2024-10-24.rds"))
nonzero_coef_df <- data.frame(
  id = names(nonzero_coef), # extract peptide ids
  coef = nonzero_coef, # extract nonzero coefficients
  stringsAsFactors = FALSE
)
# make sure id values in nonzero_coef_df and vir_lib match (want both to be numeric)
nonzero_coef_df <- nonzero_coef_df %>% 
  mutate(id = as.numeric(id))

# map back to peptides by descending order of LASSO coefficients
tmp_desc_coef <- vir_lib %>% 
  inner_join(nonzero_coef_df, by = "id") %>%
  select(coef, everything()) %>%
  arrange(desc(coef))

```
